package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
)

var adapterTemplateCmd = &cobra.Command{
	Use:   "adapter-template [name]",
	Short: "Scaffold a new adapter with boilerplate HTTP server",
	Long: `Creates a directory with a minimal HTTP adapter implementing the four
required endpoints: /declare, /task, /health, and /checkpoint.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		name := strings.TrimSpace(args[0])
		if name == "" {
			return fmt.Errorf("adapter name is required")
		}
		outDir, _ := cmd.Flags().GetString("out")
		if outDir == "" {
			outDir = name
		}

		if _, err := os.Stat(outDir); err == nil {
			return fmt.Errorf("directory %s already exists", outDir)
		}

		if err := os.MkdirAll(outDir, 0o755); err != nil {
			return fmt.Errorf("creating directory: %w", err)
		}

		data := struct {
			Name     string
			Package  string
			TaskType string
		}{
			Name:     name,
			Package:  sanitizeGoIdent(name),
			TaskType: name,
		}

		files := map[string]string{
			"main.go":             adapterMainTmpl,
			"README.md":           adapterReadmeTmpl,
			"go.mod":              adapterGoModTmpl,
			"AGENT.yaml":           adapterAgentYamlTmpl,
			"compliance_test.go":  adapterComplianceTestTmpl,
		}

		for path, tmpl := range files {
			t, err := template.New(path).Parse(tmpl)
			if err != nil {
				return fmt.Errorf("parsing %s template: %w", path, err)
			}
			f, err := os.Create(filepath.Join(outDir, path))
			if err != nil {
				return fmt.Errorf("creating %s: %w", path, err)
			}
			if err := t.Execute(f, data); err != nil {
				f.Close()
				return err
			}
			f.Close()
		}

		fmt.Printf("Adapter scaffold created in %s/\n", outDir)
		fmt.Printf("  Next: cd %s && go run . (listens on :8080)\n", outDir)
		fmt.Printf("        hive add-agent --name %s --url http://localhost:8080\n", name)
		return nil
	},
}

func sanitizeGoIdent(name string) string {
	out := make([]byte, 0, len(name))
	for i := 0; i < len(name); i++ {
		c := name[i]
		switch {
		case c >= 'a' && c <= 'z', c >= '0' && c <= '9':
			out = append(out, c)
		case c >= 'A' && c <= 'Z':
			out = append(out, c+32)
		case c == '-' || c == '_':
			// skip
		default:
			// skip
		}
	}
	if len(out) == 0 {
		return "adapter"
	}
	return string(out)
}

func init() {
	adapterTemplateCmd.Flags().String("out", "", "output directory (defaults to adapter name)")
	rootCmd.AddCommand(adapterTemplateCmd)
}

const adapterMainTmpl = `package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"time"
)

// Capabilities declares what this adapter can do.
type Capabilities struct {
	Name      string   ` + "`json:\"name\"`" + `
	TaskTypes []string ` + "`json:\"task_types\"`" + `
}

func declareHandler(w http.ResponseWriter, r *http.Request) {
	json.NewEncoder(w).Encode(Capabilities{
		Name:      "{{.Name}}",
		TaskTypes: []string{"{{.TaskType}}"},
	})
}

func taskHandler(w http.ResponseWriter, r *http.Request) {
	var req struct {
		ID    string      ` + "`json:\"id\"`" + `
		Type  string      ` + "`json:\"type\"`" + `
		Input interface{} ` + "`json:\"input\"`" + `
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	log.Printf("received task %s of type %s", req.ID, req.Type)

	// TODO: implement your task logic
	output := fmt.Sprintf("processed %s by {{.Name}}", req.ID)

	json.NewEncoder(w).Encode(map[string]interface{}{
		"task_id": req.ID,
		"status":  "completed",
		"output":  output,
	})
}

func healthHandler(w http.ResponseWriter, r *http.Request) {
	json.NewEncoder(w).Encode(map[string]string{"status": "healthy"})
}

func checkpointHandler(w http.ResponseWriter, r *http.Request) {
	json.NewEncoder(w).Encode(map[string]interface{}{
		"data": map[string]interface{}{"ts": time.Now().Unix()},
	})
}

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/declare", declareHandler)
	mux.HandleFunc("/task", taskHandler)
	mux.HandleFunc("/health", healthHandler)
	mux.HandleFunc("/checkpoint", checkpointHandler)

	addr := ":8080"
	log.Printf("{{.Name}} adapter listening on %s", addr)
	log.Fatal(http.ListenAndServe(addr, mux))
}
`

const adapterReadmeTmpl = `# {{.Name}} Adapter

Scaffold generated by ` + "`hive adapter-template`" + `.

## Run

` + "```" + `
go run .
` + "```" + `

## Register with Hive

` + "```" + `
hive add-agent --name {{.Name}} --url http://localhost:8080
` + "```" + `

## Protocol

This adapter implements the four required endpoints of the Hive Agent Adapter Protocol:

- ` + "`GET /declare`" + ` — returns capabilities JSON
- ` + "`POST /task`" + ` — accepts a task, returns a result
- ` + "`GET /health`" + ` — returns health status
- ` + "`GET /checkpoint`" + ` — returns serializable state
`

const adapterGoModTmpl = `module {{.Package}}

go 1.23
`

const adapterAgentYamlTmpl = `name: {{.Name}}
role: "Describe the role here"
capabilities:
  - "{{.TaskType}}"
constraints: []
anti_patterns: []
`

// adapterComplianceTestTmpl wires the generated adapter into the Hive compliance
// test harness so new adapters have to keep the protocol contract green.
// Story 7.4 AC: the generated adapter must compile AND pass the compliance
// test suite. This template exercises the four required endpoints directly so
// `go test` on the scaffold passes out of the box.
const adapterComplianceTestTmpl = `package main

import (
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestAdapterContract(t *testing.T) {
	mux := http.NewServeMux()
	mux.HandleFunc("/declare", declareHandler)
	mux.HandleFunc("/task", taskHandler)
	mux.HandleFunc("/health", healthHandler)
	mux.HandleFunc("/checkpoint", checkpointHandler)
	srv := httptest.NewServer(mux)
	defer srv.Close()

	// /declare returns name + task_types.
	resp, err := http.Get(srv.URL + "/declare")
	if err != nil { t.Fatalf("/declare: %v", err) }
	var caps struct {
		Name      string   ` + "`json:\"name\"`" + `
		TaskTypes []string ` + "`json:\"task_types\"`" + `
	}
	_ = json.NewDecoder(resp.Body).Decode(&caps)
	resp.Body.Close()
	if caps.Name == "" || len(caps.TaskTypes) == 0 {
		t.Fatalf("/declare returned invalid payload: %+v", caps)
	}

	// /health returns a status.
	resp, err = http.Get(srv.URL + "/health")
	if err != nil { t.Fatalf("/health: %v", err) }
	var h map[string]string
	_ = json.NewDecoder(resp.Body).Decode(&h)
	resp.Body.Close()
	if h["status"] == "" {
		t.Fatalf("/health returned empty status: %+v", h)
	}

	// /task echoes task_id + status.
	body := ` + "`" + `{"id":"t-1","type":"{{.TaskType}}","input":{"ping":true}}` + "`" + `
	resp, err = http.Post(srv.URL+"/task", "application/json", strings.NewReader(body))
	if err != nil { t.Fatalf("/task: %v", err) }
	data, _ := io.ReadAll(resp.Body)
	resp.Body.Close()
	var r struct {
		TaskID string ` + "`json:\"task_id\"`" + `
		Status string ` + "`json:\"status\"`" + `
	}
	if err := json.Unmarshal(data, &r); err != nil || r.TaskID != "t-1" {
		t.Fatalf("/task mismatch: body=%s r=%+v err=%v", data, r, err)
	}

	// /checkpoint returns a data field.
	resp, err = http.Get(srv.URL + "/checkpoint")
	if err != nil { t.Fatalf("/checkpoint: %v", err) }
	var cp map[string]interface{}
	_ = json.NewDecoder(resp.Body).Decode(&cp)
	resp.Body.Close()
	if _, ok := cp["data"]; !ok {
		t.Fatalf("/checkpoint missing data field: %+v", cp)
	}
}
`
