package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
)

var adapterTemplateCmd = &cobra.Command{
	Use:   "adapter-template [name]",
	Short: "Scaffold a new adapter with boilerplate HTTP server",
	Long: `Creates a directory with a minimal HTTP adapter implementing the four
required endpoints: /declare, /task, /health, and /checkpoint.`,
	Args: cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		name := strings.TrimSpace(args[0])
		if name == "" {
			return fmt.Errorf("adapter name is required")
		}
		outDir, _ := cmd.Flags().GetString("out")
		if outDir == "" {
			outDir = name
		}

		if _, err := os.Stat(outDir); err == nil {
			return fmt.Errorf("directory %s already exists", outDir)
		}

		if err := os.MkdirAll(outDir, 0o755); err != nil {
			return fmt.Errorf("creating directory: %w", err)
		}

		data := struct {
			Name     string
			Package  string
			TaskType string
		}{
			Name:     name,
			Package:  sanitizeGoIdent(name),
			TaskType: name,
		}

		files := map[string]string{
			"main.go":    adapterMainTmpl,
			"README.md":  adapterReadmeTmpl,
			"go.mod":     adapterGoModTmpl,
			"AGENT.yaml": adapterAgentYamlTmpl,
		}

		for path, tmpl := range files {
			t, err := template.New(path).Parse(tmpl)
			if err != nil {
				return fmt.Errorf("parsing %s template: %w", path, err)
			}
			f, err := os.Create(filepath.Join(outDir, path))
			if err != nil {
				return fmt.Errorf("creating %s: %w", path, err)
			}
			if err := t.Execute(f, data); err != nil {
				f.Close()
				return err
			}
			f.Close()
		}

		fmt.Printf("Adapter scaffold created in %s/\n", outDir)
		fmt.Printf("  Next: cd %s && go run . (listens on :8080)\n", outDir)
		fmt.Printf("        hive add-agent --name %s --url http://localhost:8080\n", name)
		return nil
	},
}

func sanitizeGoIdent(name string) string {
	out := make([]byte, 0, len(name))
	for i := 0; i < len(name); i++ {
		c := name[i]
		switch {
		case c >= 'a' && c <= 'z', c >= '0' && c <= '9':
			out = append(out, c)
		case c >= 'A' && c <= 'Z':
			out = append(out, c+32)
		case c == '-' || c == '_':
			// skip
		default:
			// skip
		}
	}
	if len(out) == 0 {
		return "adapter"
	}
	return string(out)
}

func init() {
	adapterTemplateCmd.Flags().String("out", "", "output directory (defaults to adapter name)")
	rootCmd.AddCommand(adapterTemplateCmd)
}

const adapterMainTmpl = `package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"time"
)

// Capabilities declares what this adapter can do.
type Capabilities struct {
	Name      string   ` + "`json:\"name\"`" + `
	TaskTypes []string ` + "`json:\"task_types\"`" + `
}

func declareHandler(w http.ResponseWriter, r *http.Request) {
	json.NewEncoder(w).Encode(Capabilities{
		Name:      "{{.Name}}",
		TaskTypes: []string{"{{.TaskType}}"},
	})
}

func taskHandler(w http.ResponseWriter, r *http.Request) {
	var req struct {
		ID    string      ` + "`json:\"id\"`" + `
		Type  string      ` + "`json:\"type\"`" + `
		Input interface{} ` + "`json:\"input\"`" + `
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	log.Printf("received task %s of type %s", req.ID, req.Type)

	// TODO: implement your task logic
	output := fmt.Sprintf("processed %s by {{.Name}}", req.ID)

	json.NewEncoder(w).Encode(map[string]interface{}{
		"task_id": req.ID,
		"status":  "completed",
		"output":  output,
	})
}

func healthHandler(w http.ResponseWriter, r *http.Request) {
	json.NewEncoder(w).Encode(map[string]string{"status": "healthy"})
}

func checkpointHandler(w http.ResponseWriter, r *http.Request) {
	json.NewEncoder(w).Encode(map[string]interface{}{
		"data": map[string]interface{}{"ts": time.Now().Unix()},
	})
}

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/declare", declareHandler)
	mux.HandleFunc("/task", taskHandler)
	mux.HandleFunc("/health", healthHandler)
	mux.HandleFunc("/checkpoint", checkpointHandler)

	addr := ":8080"
	log.Printf("{{.Name}} adapter listening on %s", addr)
	log.Fatal(http.ListenAndServe(addr, mux))
}
`

const adapterReadmeTmpl = `# {{.Name}} Adapter

Scaffold generated by ` + "`hive adapter-template`" + `.

## Run

` + "```" + `
go run .
` + "```" + `

## Register with Hive

` + "```" + `
hive add-agent --name {{.Name}} --url http://localhost:8080
` + "```" + `

## Protocol

This adapter implements the four required endpoints of the Hive Agent Adapter Protocol:

- ` + "`GET /declare`" + ` — returns capabilities JSON
- ` + "`POST /task`" + ` — accepts a task, returns a result
- ` + "`GET /health`" + ` — returns health status
- ` + "`GET /checkpoint`" + ` — returns serializable state
`

const adapterGoModTmpl = `module {{.Package}}

go 1.23
`

const adapterAgentYamlTmpl = `name: {{.Name}}
role: "Describe the role here"
capabilities:
  - "{{.TaskType}}"
constraints: []
anti_patterns: []
`
