-- Migration 025 : meme drop que SQLite, avec CASCADE pour tolerer les
-- FK persistantes entre tables pre-pivot.

DROP TABLE IF EXISTS agent_tokens CASCADE;
DROP TABLE IF EXISTS agent_trust_overrides CASCADE;
DROP TABLE IF EXISTS agents CASCADE;
DROP TABLE IF EXISTS api_keys CASCADE;
DROP TABLE IF EXISTS auctions CASCADE;
DROP TABLE IF EXISTS bids CASCADE;
DROP TABLE IF EXISTS budget_alerts CASCADE;
DROP TABLE IF EXISTS cluster_members CASCADE;
DROP TABLE IF EXISTS costs CASCADE;
DROP TABLE IF EXISTS dialog_messages CASCADE;
DROP TABLE IF EXISTS dialog_threads CASCADE;
DROP TABLE IF EXISTS federation_links CASCADE;
DROP TABLE IF EXISTS invoices CASCADE;
DROP TABLE IF EXISTS knowledge CASCADE;
DROP TABLE IF EXISTS optimizations CASCADE;
DROP TABLE IF EXISTS rbac_users CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS trust_history CASCADE;
DROP TABLE IF EXISTS webhook_deliveries CASCADE;
DROP TABLE IF EXISTS webhooks CASCADE;
DROP TABLE IF EXISTS workflows CASCADE;
